<a href="https://colab.research.google.com/github/forkedroads/jupyter-notebooks/blob/master/hello_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!python --version

Python 3.6.9


In [25]:
py_a = [[1,2,3],[4,5,6],[7,8,9]]
print(py_a[:2])

[[1, 2, 3], [4, 5, 6]]


In [3]:
import numpy as np


In [30]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
print(a[:2])
print(a[0:1, 1:3])
print(a[1][2:3])

[[1 2 3 4]
 [5 6 7 8]]
[[2 3]]
[7]


In [27]:
r = (a[1:2] )
print(r)
print(r.shape)

[[5 6 7 8]]
(1, 4)


In [29]:
col = a[:, 0:1]
print(col)

[[1]
 [5]
 [9]]


In [31]:
print(np.arange(4))

[0 1 2 3]


In [33]:
print(np.array([9,10]))

[ 9 10]


In [36]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)))

[[1]
 [2]
 [3]]
