<a href="https://colab.research.google.com/github/forkedroads/jupyter-notebooks/blob/master/hello_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!python --version

Python 3.6.9


In [25]:
py_a = [[1,2,3],[4,5,6],[7,8,9]]
print(py_a[:2])

[[1, 2, 3], [4, 5, 6]]


In [3]:
import numpy as np


In [26]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[:2])
print(a[0:1, 1:3])
print(a[1][2:3])

[[1 2 3 4]
 [5 6 7 8]]
[[2 3]]
[7]


In [27]:
r = (a[1:2] )
print(r)
print(r.shape)

[[5 6 7 8]]
(1, 4)
